#!/bin/sh
alias compress_image="php ${DATA_HOARDING_PATH}/scripts/compress_image.php"
alias compress_video="php ${DATA_HOARDING_PATH}/scripts/compress_video.php"
alias compare_video="php ${DATA_HOARDING_PATH}/scripts/compare_video.php"
alias extract_exif="php ${DATA_HOARDING_PATH}/scripts/extract_exif.php"
alias rename_media="php ${DATA_HOARDING_PATH}/scripts/rename_media.php"
alias stabilize_video="php ${DATA_HOARDING_PATH}/scripts/stabilize_video.php"
alias shift_exif_date="php ${DATA_HOARDING_PATH}/scripts/shift_exif_date.php"
alias assemble_dashcam_jansite="php ${DATA_HOARDING_PATH}/scripts/assemble_dashcam_jansite.php"
alias assemble_dashcam_viofo="php ${DATA_HOARDING_PATH}/scripts/assemble_dashcam_viofo.php"
